apiVersion: apps/v1
kind: Deployment
metadata:
  name: celery-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: celery-worker
  template:
    metadata:
      labels:
        app: celery-worker
    spec:
      containers:
      - name: celery-worker-container
        image: tvilarim/pdf-db-creator:latest
        command: ["celery", "-A", "app.celery", "worker", "--loglevel=info"]
        env:
        - name: CELERY_BROKER_URL
          value: "redis://redis:6379/0"
        - name: CELERY_RESULT_BACKEND
          value: "redis://redis:6379/0"
        volumeMounts:
        - name: uploads-volume
          mountPath: /app/uploads  # O mesmo caminho de uploads
      volumes:
      - name: uploads-volume
        emptyDir: {}  # Mesma configuração de volume compartilhado
