apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: pdf-db-creator-hpa
  version: v1.29
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: pdf-db-creator
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
