apiVersion: v1
kind: Service
metadata:
  name: pdf-db-creator
  version: v1.27
spec:
  type: NodePort
  selector:
    app: pdf-db-creator
  ports:
    - protocol: TCP
      port: 5000  # Porta do container Flask
      targetPort: 5000
      nodePort: 30000  # Porta externa que será acessível
