apiVersion: apps/v1
kind: Deployment
metadata:
  name: pdf-db-creator
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pdf-db-creator
  template:
    metadata:
      labels:
        app: pdf-db-creator
        version: v1.30
    spec:
      containers:
      - name: pdf-db-creator-container
        image: tvilarim/pdf-db-creator:latest
        ports:
        - containerPort: 5000
        volumeMounts:
        - name: uploads-volume
          mountPath: /app/uploads  # O caminho onde os arquivos são salvos
      volumes:
      - name: uploads-volume
        emptyDir: {}  # Volume temporário que será compartilhado entre containers
