apiVersion: apps/v1
kind: Deployment
metadata:
  name: pdf-db-creator
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pdf-db-creator
  template:
    metadata:
      labels:
        app: pdf-db-creator
        version: v1.27
    spec:
      containers:
      - name: pdf-db-creator-container
        image: tvilarim/pdf-db-creator:latest
        ports:
        - containerPort: 5000
        env:
        - name: CELERY_BROKER_URL
          value: "redis://redis:6379/0"
        - name: CELERY_RESULT_BACKEND
          value: "redis://redis:6379/0"
        resources:
          requests:
            cpu: "200m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
