apiVersion: v1
kind: Service
metadata:
  name: pdf-db-creator-service
spec:
  selector:
    app: pdf-db-creator
  ports:
    - protocol: TCP
      port: 80         # Porta interna usada no contêiner (porta de destino)
      targetPort: 5000  # Porta do Flask no contêiner
      nodePort: 30000   # Porta fixa na rede local
  type: NodePort       # Expondo o serviço como NodePort
