apiVersion: v1
kind: Service
metadata:
  name: pdf-db-creator-service
spec:
  selector:
    app: pdf-db-creator
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer
